### ISSUE TITLE
Floating IPs

### ISSUE THREAD

**Issue by keyurshah** [jasonheecs/ansible-digitalocean-sample-playbook#11]
Thanks for this project!

Wondering what the best way to work with floating IPs would be using this playbook? 

Whether there are existing empty floating IPs or provisioning new ones

**Comment by jasonheecs** [comment]
Hey, if you have an existing IP tied to a droplet, you can add that ip to the hosts file, eg:

```
[do_droplet_in_memory]
droplet-name ansible_host=192.168.x.x
```

To provision new floating IPs or assigning existing floating IPs to droplets, you will probably need to add a new ansible task like https://github.com/inviqa/ansible-digitalocean-floating-ip into the playbook.
